// generated by stringer -type=InCommand; DO NOT EDIT

package main

import "fmt"

const _InCommand_name = "CommandIncNoneCommandIncAcceptCommandIncConnectCommandIncKeysCommandIncInitPRNGCommandIncStatsCommandIncChangeConnid"

var _InCommand_index = [...]uint8{0, 14, 30, 47, 61, 79, 94, 116}

func (i InCommand) String() string {
	if i < 0 || i+1 >= InCommand(len(_InCommand_index)) {
		return fmt.Sprintf("InCommand(%d)", i)
	}
	return _InCommand_name[_InCommand_index[i]:_InCommand_index[i+1]]
}
